
### OBTÊM TODOS OS PRODUTOS PAGINADO DE 10 EM 10
GET http://localhost:3000/products

### CRIA UM PRODUTO
POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "Monitor Gamer Dell",
    "slug": "monitor-gamer",
    "description": "Monitor gamer de alta performance com resolução QHD para imagens nítidas.",
    "price": 2999.50
}

### OBTÊM UM UNICO PRODUTO
GET http://localhost:3000/products/c95b07d3-5c13-4e6f-b60b-1bd778c884c7

### OBTÊM UM UNICO PRODUTO PELO NOME
GET http://localhost:3000/products?name=notebook

### ATUALIZA UM PRODUTO
PATCH http://localhost:3000/products/c95b07d3-5c13-4e6f-b60b-1bd778c884c7
Content-Type: application/json

{
    "name": "Monitor Gamer Dell xxxx",
    "slug": "monitor-gamer-x",
    "description": "Monitor gamer xxxxxx",
    "price": 2999.50
}

### EXCLUI UM PRODUTO
DELETE http://localhost:3000/products/3d894160-d2ec-41e8-a314-1f791b55e7d7