
###
GET http://localhost:3000/products

###
POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "Monitor Gamer Dell",
    "slug": "monitor-gamer",
    "description": "Monitor gamer de alta performance com resolução QHD para imagens nítidas.",
    "price": 2999.50
}

###
GET http://localhost:3000/products/cmahlxvms000068woi40fq5ly

###
PATCH http://localhost:3000/products/3d894160-d2ec-41e8-a314-1f791b55e7d7
Content-Type: application/json

{
    "name": "Monitor Gamer Dell",
    "slug": "monitor-gamer-dell",
    "description": "Monitor gamer de alta performance com resolução QHD para imagens nítidas.",
    "price": 2999.50
}

###
DELETE http://localhost:3000/products/3d894160-d2ec-41e8-a314-1f791b55e7d7